spec_version: 1.2
package: hicdex

advanced:
  early_realtime: True
  merge_subscriptions: True
  postpone_jobs: True
    
database:
  kind: sqlite
  path: hic_et_nunc.sqlite3
  immune_tables:
    - token_metadata
    - contract_metadata
    - ignored_cids

contracts:
  HEN_objkts:
    address: KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton
    typename: hen_objkts
  HEN_swap_v1:
    address: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
    typename: hen_minter
  HEN_swap_v2:
    address: KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn
    typename: hen_swap_v2
  HENC_swap:
    address: KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w
    typename: henc_swap
  HEN_subjkts:
    address: KT1My1wDZHDGweCrJnQJi3wcFaS67iksirvj
    typename: hen_subjkt
  HDAO_curation:
    address: KT1TybhR7XraG75JFYKSrh7KnxukMBT5dor6
    typename: hdao_curation
  HDAO_ledger:
    address: KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW
    typename: hdao_ledger
  SPLIT_contract_sample_a:
    address: KT1K8A2cqqpQTEHYpY9R7aAybCdcM3tNpXyu
    typename: split_contract_a
  SPLIT_contract_sample_b:
    address: KT1Nr12oNBxMXqrgWPaN7tedue8Q6GzzbiNg
    typename: split_contract_a
  SPLIT_contract_sample_c:
    address: KT1Uaq7E1zcTg2BCDXWXBmuGoVFeLZkCkv3s
    typename: split_contract_a
  SPLIT_contract_sample_d:
    address: KT1XNKmW2786FRK9rGr544JYcmLvcvwn3qEV
    typename: split_contract_a
  SPLIT_contract_sample_e:
    address: KT1NcoBQJ5PbGNWCcchhKeYdopvmvugZdeCg
    typename: split_contract_b
  SPLIT_contract_sample_f:
    address: KT1SDPuVqjsuRNDUKemXYyadTHHrDJy1sqjc
    typename: split_contract_b
  SPLIT_sign:
    address: KT1BcLnWRziLDNJNRn3phAANKrEBiXhytsMY
    typename: split_sign

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: https://api.tzkt.io
  metadata:
    kind: metadata
    url: https://api-metadata.teia.rocks
    network: mainnet
  ipfs:
    kind: ipfs
    url: https://ipfs.teia.rocks/ipfs
    http:
      retry_count: 1
      retry_sleep: 1
      batch_size: 100
  fallback_ipfs:
    kind: ipfs
    url: https://nftstorage.link/ipfs
    http:
      retry_count: 2
      retry_sleep: 1
      batch_size: 100
      ratelimit_rate: 200
      ratelimit_period: 60
  fallback2_ipfs:
    kind: ipfs
    url: https://ipfs.io/ipfs
    http:
      retry_count: 2
      retry_sleep: 1
      batch_size: 100
  bcd:
    kind: http
    url: https://api.better-call.dev/v1

indexes:
  hen_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    types:
      - transaction
      - origination
    contracts:
      - HEN_swap_v1
      - HEN_swap_v2
      - HENC_swap
      - HEN_objkts
      - HEN_subjkts
      - HDAO_curation
      - HDAO_ledger
      - SPLIT_sign
    handlers:
      # marketplace v1
      - callback: on_mint
        pattern:
          - type: transaction
            destination: HEN_swap_v1
            entrypoint: mint_OBJKT
          - type: transaction
            destination: HEN_objkts
            entrypoint: mint
      - callback: on_swap
        pattern:
          - type: transaction
            destination: HEN_swap_v1
            entrypoint: swap
      - callback: on_cancel_swap
        pattern:
          - type: transaction
            destination: HEN_swap_v1
            entrypoint: cancel_swap
      - callback: on_collect
        pattern:
          - type: transaction
            destination: HEN_swap_v1
            entrypoint: collect

      # marketplace v2
      - callback: on_swap_v2
        pattern:
          - type: transaction
            destination: HEN_swap_v2
            entrypoint: swap
      - callback: on_cancel_swap_v2
        pattern:
          - type: transaction
            destination: HEN_swap_v2
            entrypoint: cancel_swap
      - callback: on_collect_v2
        pattern:
          - type: transaction
            destination: HEN_swap_v2
            entrypoint: collect

      # marketplace henc
      - callback: on_swap_henc
        pattern:
          - type: transaction
            destination: HENC_swap
            entrypoint: swap
      - callback: on_cancel_swap_henc
        pattern:
          - type: transaction
            destination: HENC_swap
            entrypoint: cancel_swap
      - callback: on_collect_henc
        pattern:
          - type: transaction
            destination: HENC_swap
            entrypoint: collect

      # fa2
      - callback: on_transfer
        pattern:
          - type: transaction
            destination: HEN_objkts
            entrypoint: transfer

      # subjkt
      - callback: on_subjkt_register
        pattern:
          - type: transaction
            destination: HEN_subjkts
            entrypoint: registry
      # hdao
      - callback: on_hdaol_batch
        pattern:
          - type: transaction
            destination: HDAO_ledger
            entrypoint: hDAO_batch
      - callback: on_hdaol_transfer
        pattern:
          - type: transaction
            destination: HDAO_ledger
            entrypoint: transfer

      - callback: on_hdaoc_claim
        pattern:
          - type: transaction
            destination: HDAO_curation
            entrypoint: claim_hDAO
      - callback: on_hdaoc_curate
        pattern:
          - type: transaction
            destination: HDAO_curation
            entrypoint: curate

      # operators
      - callback: on_operator_update
        pattern:
          - type: transaction
            destination: HEN_objkts
            entrypoint: update_operators

      # split sign
      - callback: on_split_sign
        pattern:
          - type: transaction
            destination: SPLIT_sign
            entrypoint: sign

  split_contract_a:
    kind: operation
    datasource: tzkt_mainnet
    types:
      - transaction
      - origination
    handlers:
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_a
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_b
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_c
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_d

  split_contract_b:
    kind: operation
    datasource: tzkt_mainnet
    types:
      - transaction
      - origination
    handlers:
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_e
      - callback: on_split_contract_origination_a
        pattern:
          - type: origination
            similar_to: SPLIT_contract_sample_f

hooks:
  fix_missing_metadata:
    callback: fix_missing_metadata

jobs:
  fix_missing_metadata:
    hook: fix_missing_metadata
    interval: 300

logging: quiet
